### ISSUE TITLE
Property Statements are Allows in Annex Libraries While Equations are Not

### ISSUE THREAD

**Issue by philip-alldredge** [smaccm/smaccm#103]
Equation statements are only allowed in Annex subclauses. However, property statements are allowed in annex libraries as well. Is this intended? Since, property statements are equivalent to equations of type bool, I would expect it to not be allowed.

**Comment by kfhoech** [comment]
This is likely an oversight.  Because annex libraries really do not have instances, the logic of property statements is unclear in the context of the instance model.

The safe solution is to disallow property statements in annex libraries.

**Comment by kfhoech** [comment]
Resolved by [Pull Request](https://github.com/smaccm/smaccm/pull/107),
