### ISSUE TITLE
Can I define contracts for a subprogram ?

### ISSUE THREAD

**Issue by paolo-crisafulli** [smaccm/smaccm#116]
Hi,
I would like to define contracts for subprograms, involving their in and out parameters.
Is this supported ?

The simple model below reports an error.

Thank you very much for your help.

	package agree_subprogram
	public
		with Base_Types;

		subprogram vote
			features
				x: in parameter Base_Types::Float;
				result: out parameter Base_Types::Float;
			annex agree {**
				assume "something": x > 0.0;   -- this reports an error
				assume "somethingelse ": 0 = 0;   -- this works
			**};
		end vote;

	end agree_subprogram;

**Comment by janetlj** [comment]
AGREE does not support reasoning over subprograms in AADL. 

Here are the rationales collected from John Backes in 2017:

1. Subprograms are meant to model procedure calls. The semantics of procedures do not really line up with AGREE. 

For example, if A calls B, and B calls C, then C should finish before B, and B should finish before A. This does not really line up with how AGREE model computation. 

AGREE model state transitions that occur in components; components can behave synchronously, or users can specify constraints for their clocks. Subprograms don't really map onto this paradigm. For example, subprograms can call themselves recursively.

2. Subprograms in AADL are modeling behaviors at an abstraction level that is much lower than what we typically want to reason about in AADL. For example, we could model the subprograms in Simulink and export its parent level AGREE contracts into the Simulink environment to verify them.

**Comment by paolo-crisafulli** [comment]
Ok, thank you for your kind answer.
