### ISSUE TITLE
Use of AADL types for equations and constants in AGREE annex

### ISSUE THREAD

**Issue by mwwhalen** [smaccm/smaccm#12]
AGREE can use AADL types from outside the AGREE annex clause, but you can't write them as types within the AGREE subclause for equations and constants.

system Mode_Control
    features
        start: in data port Base_Types::Boolean;
        clear: in data port Base_Types::Boolean;
        cooking_mode: out data port Base_Types::Integer;

```
annex agree {** 
           -- syntax error here.
    eq is_cooking : Base_Types::Boolean = defs.is_cooking(cooking_mode); 
```

**Comment by kfhoech** [comment]
If we concur that the mapping from AADL types to AGREE types is sufficiently well understood, then this makes sense.  We already do the mapping implicitly for elements of aggregates; there are already plenty of implicit mappings occurring already.

**Comment by kfhoech** [comment]
Resolved by [Pull Request](https://github.com/smaccm/smaccm/pull/120).
