### ISSUE TITLE
Resolute: how to define a range? 

### ISSUE THREAD

**Issue by paolo-crisafulli** [smaccm/smaccm#162]
Hi,
Resolute supports the range as a built-in type.
But I did not find any way to define a range constant.
I have tried:
`let r : range = [0..1];`
`let r : range = 0..1;`
`let r : range = range(0,1);`
Found  nothing in the doc either.
Could you state what the correct syntax is?
Thank you in advance.
Paolo

**Comment by paolo-crisafulli** [comment]
I think I have misunderstood the range type then.
My use case is the following:
I want to create a list containing the first n integers, starting from 0.
As I understand it now, the range type is not what I was looking for, which raises two questions:
1/ How would you deal with the use case I have described within Resolute?
2/ Do you have a pointer (doc or code) illustrating the use of the range type you described?

Thank you very much in advance.

Best regards,
Paolo

**Comment by kfhoech** [comment]
In general we try to keep the Resolute language as compact as possible, preferring to define features where possible in libraries.  It implement the generation of a range of scalars between two bounds, can be approached by definition of a recursive computational function and a wrapper to pretty the syntax.

~~~~~
	int_range_rec(l : [int], lower: int, upper : int) : [int] =
		if upper < lower then l else append(int_range_rec(l,lower,upper-1),[upper])
	int_range(lower : int, upper : int) : [int] =
		int_range_rec([], lower, upper)
~~~~~

These can then be accessed from a claim by the following

~~~~~
	Range_1234 (self : component) <=
		** "Range 1234" **
		[1, 2, 3, 4] = int_range(1,4)
~~~~~

To answer your other question regarding range, a simple example might examine the load time property for a system

~~~~~
package Issue_162_Pkg
public

	annex resolute {**
		Load_Time_Acceptable(self : component, lower : int, upper : int) <=
			** "Load time is reasonable " **
			has_property(self, Timing_Properties::Load_Time) andthen
			(let load_time_range : range = property(self, Timing_Properties::Load_Time);
				lower <= lower_bound(load_time_range) and upper_bound(load_time_range) <= upper)
	**};

	system Issue_162_A
	end Issue_162_A;

	system implementation Issue_162_A.Impl
		properties
			Timing_Properties::Load_Time => 5 ms .. 10 ms; 
		annex resolute {**
			prove(Load_Time_Acceptable(this, 2000000000, 11000000000))
		**};
	end Issue_162_A.Impl;

end Issue_162_Pkg;
~~~~~

Note: in AADL, time property values are integer numbers of picoseconds, but may be scaled by giving units as done in the property association.

Thanks for using Resolute!

**Comment by paolo-crisafulli** [comment]
My pleasure :-)
Thank you for yor very informative answer!
