### ISSUE TITLE
Can't refer to contract constants inside a node

### ISSUE THREAD

**Issue by spmiller2055** [smaccm/smaccm#30]
If a contract contains a node that refers to a constant defined in the contract, it is flagged as an error. For example, 

annex agree {**
  const Max : int = 10;

```
node x(i: int) returns (r: int);
let r = i; 

lemma "W" : i <= Max;
```

tel;

flags the the reference to Max as an error.

**Comment by kfhoech** [comment]
Resolved by [Pull Request](https://github.com/smaccm/smaccm/pull/120).
