### ISSUE TITLE
Installation Error - Update Site Broken?

### ISSUE THREAD

**Issue by smithdtyler** [smaccm/smaccm#52]
When I try to install tools from

`​https://raw.githubusercontent.com/smaccm/update-site/master`

I get:

```
An error occurred while collecting items to be installed
session context was:(profile=epp.package.rcp, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: ​https://raw.githubusercontent.com/smaccm/update-site/master/plugins/edu.umn.cs.crisys.smaccm.aadl2rtos_1.0.0.201608151447.jar.
​https://raw.githubusercontent.com/smaccm/update-site/master/plugins/edu.umn.cs.crisys.smaccm.aadl2rtos_1.0.0.201608151447.jar
Artifact not found: ​https://raw.githubusercontent.com/smaccm/update-site/master/features/edu.umn.cs.crisys.smaccm.aadl2rtos.feature_1.0.0.201608151447.jar.
​https://raw.githubusercontent.com/smaccm/update-site/master/features/edu.umn.cs.crisys.smaccm.aadl2rtos.feature_1.0.0.201608151447.jar
```

**Comment by backesj** [comment]
Hi Tyler,

It looks like that jar for the trusted build is missing from our repo. I'll
go ahead and build a new version of the plugin and push it to the update
site.

- John

**Comment by backesj** [comment]
Go ahead and give it a try now.

**Comment by smithdtyler** [comment]
Hmm.. same error. I'll try again later tonight.

**Comment by backesj** [comment]
Are you adding the "site.xml" file to the end of the link when you enter it
into your update site? E.g.,:

https://raw.githubusercontent.com/smaccm/update-site/master/site.xml

- John

**Comment by smithdtyler** [comment]
Using the URL with `site.xml` the install completed successfully.  Thanks for the assistance.
