### ISSUE TITLE
Separate contributed AADL from genmodel in Agree

### ISSUE THREAD

**Issue by joeseibel** [smaccm/smaccm#66]
The plugin project `com.rockwellcollins.atc.agree` contains a genmodel file as well as contribued AADL files. This causes problems with the new virtualization of contributed AADL. The contributed AADL should be moved to another plugin.

See https://github.com/osate/osate2-core/issues/527#issuecomment-242180193.

**Comment by kfhoech** [comment]
Close issue as joeseibel already completed the effort.
