### ISSUE TITLE
AGREE User Guide References Missing Figures

### ISSUE THREAD

**Issue by philip-alldredge** [smaccm/smaccm#88]
The markdown for the AGREE User Guide references Figure 14 and Figure 15 which doesn't exist.  See Section "Advanced Topic: Linearization Definitions"

**Comment by kfhoech** [comment]
Yes, the text was apparently not correctly updated when the document was converted to markdown.

Thanks, Philip!

**Comment by kfhoech** [comment]
Updated in [pull request](https://github.com/smaccm/smaccm/pull/89).
